version: 2.1

jobs:
  run_test:
    docker:
      - image: circleci/python:3.9.6
    steps:
      - checkout
      - run:
          name: install dependencies and run
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
            python test/tets.py

workflows:
  build_test:
    jobs:
      - run_test
